package-lock.json
package.json
public/locales/en/translation.json
public/locales/pl/translation.json
public/locales/ru/translation.json
public/locales/ua/translation.json
src/App.js
src/Components/Details/Details.css
src/Components/Details/Details.js
src/Components/Details/Details.test.js
src/Components/MoreEventsFromOrganizer/MoreEvents.css
src/Components/MoreEventsFromOrganizer/MoreEvents.js
src/Components/MoreEventsFromOrganizer/MoreEvents.test.js

Jira: https://woloapp.atlassian.net/browse/WOLO-47

WOLO 47 - Event Details

---

package-lock.json
package.json
public/locales/en/translation.json
public/locales/pl/translation.json
public/locales/ru/translation.json
public/locales/ua/translation.json
src/App.js
src/Components/AllEvents/AllEvents.css
src/Components/AllEvents/AllEvents.js
src/Components/AllEvents/AllEvents.test.js
src/Components/EventCard/EventCard.css
src/Components/EventCard/EventCard.js
src/Components/EventCard/EventCard.test.js

Jira: https://woloapp.atlassian.net/browse/WOLO-35

Wolo 35 all events

---

.githooks/pre-commmit
.husky/pre-commit
package-lock.json
package.json

+ Removed husky
+ Added .githooks/precommit
In case of any problems, revert changes

Remove Husky and replace it with another solution

---

package-lock.json
package.json

We cant get rid of some vulnerabilitys due to: https://github.com/facebook/create-react-app/issues/11174
Also if we want to aduit code we shoud use: npm audit --production

Vulnerabilit

---

src/Components/Details/Details.js
src/styles/details.scss

https://woloapp.atlassian.net/browse/WOLO-72

WOLO-72 - refactoring details

---

package-lock.json
src/Components/Filters/Filters.js

Simple fetch in order to prove that it works

Added fetch

---

package-lock.json
public/locales/en/translation.json
public/locales/pl/translation.json
public/locales/ru/translation.json
public/locales/ua/translation.json
src/Components/Hero/Hero.js
src/styles/hero.scss
src/styles/navbar.scss

Made changes of the main layout page to more fit the prototype. Added needed translations.

WOLO-73 hero and navbar refactoring

---

package-lock.json
package.json
src/App.js
src/Components/Login/Login.js
src/Components/Signup/Signup.js

What was done:
- Routing /singup /login
- Added Formik
- Structure for login

Wolo 112 login component

---

public/locales/en/translation.json
public/locales/pl/translation.json
public/locales/ru/translation.json
public/locales/ua/translation.json
src/App.js
src/Components/OrganiserEventListDisplay/OrganiserEventListDisplay.js
src/Components/OrganiserHomePage/OrganiserHomePage.js
src/styles/organiser-event-list-display.scss
src/styles/organiser-home-page.scss

https://woloapp.atlassian.net/browse/WOLO-109

Wolo 109 organiser home page

---

src/Components/Login/Login.js
src/styles/login.scss

WOLO-112 style added

---

src/App.js
src/Components/OrganiserCreateEvent/OrganiserCreateEvent.js
src/Components/OrganiserHomePage/OrganiserHomePage.js
src/styles/organiser-create-event.scss

made basic form for creating event by organiser

Wolo 108 create component for creating events by organiser

---

src/Components/Details/Details.js
src/Components/Details/ShiftCheckbox/ShiftCheckbox.js
src/styles/details.scss
src/styles/shift-checkbox.scss

Added checkboxes to pick a shift
Jira: https://woloapp.atlassian.net/browse/WOLO-119

WOLO-119-added checkboxes for shifts

---

src/App.js
src/Components/AdminHomePage/AdminHomePage.js
src/Components/AdminHomePage/EventCardToModerate/EventCardToModerate.js
src/styles/admin-home-page.scss
src/styles/event-card-to-moderate.scss

Jira: https://woloapp.atlassian.net/browse/WOLO-124
No translations

Wolo 124 admin home page (no translations)

---

public/locales/en/translation.json
public/locales/pl/translation.json
public/locales/ru/translation.json
public/locales/ua/translation.json
src/Components/AdminHomePage/AdminHomePage.js
src/Components/AdminHomePage/EventCardToModerate/EventCardToModerate.js
src/styles/admin-home-page.scss

admin home page translations and margin
Jira: https://woloapp.atlassian.net/browse/WOLO-124

Wolo 124 admin home page translations and margin

---

src/Components/Details/ShiftCheckbox/ShiftCheckbox.js

WOLO-119 - checkbox translation
Jira: https://woloapp.atlassian.net/browse/WOLO-119

WOLO-119 - checkbox translation

---

src/Components/Details/Details.js
src/Components/Details/ShiftCheckbox/ShiftCheckbox.js

Automated way of mapping shifts depending on details response

Mapping shifts

---

public/locales/en/translation.json
public/locales/pl/translation.json
public/locales/ru/translation.json
public/locales/ua/translation.json
src/Components/Filters/Filters.js
src/Components/Hero/Hero.js
src/styles/all-events.scss
src/styles/common.scss
src/styles/event-card.scss
src/styles/hero.scss

Part of Jira: https://woloapp.atlassian.net/browse/WOLO-132
In this PR:
- filters toggle button fixed
- reset filters button fixed
- hero filters on mobile fixed
- refactored hero component - deleted some stuff, added some to common.scss
- made font bigger (18px)
- event card fitting all info with no extra space underneath
- added missing translations
Right now Hero and All Events page should be completed, no fixes needed

Wolo 132   scss updates

---

public/locales/en/translation.json
public/locales/pl/translation.json
public/locales/ru/translation.json
public/locales/ua/translation.json
src/Components/Filters/Filters.js
src/Utils/fetchData.js
src/styles/all-events.scss

Add filters for location, category and age
Add translation for "Reset All Filters" in multiple languages and made style for it 
Exported fetching data to utils as a function

WOLO-129-Finishing_Filters

---

public/locales/en/translation.json
public/locales/pl/translation.json
public/locales/ru/translation.json
public/locales/ua/translation.json
src/Components/Details/Details.js
src/Components/EventCard/EventCard.js
src/Components/OrganiserCreateEvent/OrganiserCreateEvent.js
src/styles/all-events.scss
src/styles/common.scss
src/styles/details.scss
src/styles/organiser-create-event.scss

JIRA: https://woloapp.atlassian.net/browse/WOLO-132
- all events smaller margin lol
- more events form this organizer in details fixed to row and scroll
- if no picture provided don't show img - for details and event card
- organiser home page button not underlined
- translations for create event

Wolo 132 UI fixes

---

package-lock.json
package.json
src/Components/Login/Login.js
src/Components/Signup/Signup.js
src/Utils/axiosInstance.js

Połączenie systemu logowania backend z frontend
Należy pobrać env i application.properties.
W celu przetestowania wejść na stronę logowania, zbadać w stronę, wejść do network i zaznaczyć preserve log, następnie  podać email: jan.kowalski@example.com hasło: password i kliknąć zaloguj. Strona przekieruje na stronę organizatora, a w responsie powinien pojawić się token. można wrócić do logowania, zalogować się ponownie i w wysłanym requescie powinien byc poprzednio odebrany token.

Request interceptor

---

src/Components/Filters/Filters.js
src/Components/Hero/Hero.js

Fixed bug related to new shift mapping (FE would crash whenever date was selected in hero and filters)
Made Date picker and Location Picker functional
Filters from Hero apply only after clicking search button

Wolo-166-hero-filters

---

src/Components/Details/Details.js
src/Components/Details/SignInSection/SignInSection.js
src/Utils/formatDate.js
src/Utils/tests/formatDate.test.js
src/styles/details.scss

Jira: https://woloapp.atlassian.net/browse/WOLO-187
- time deleted
- date updated
- formatDate util created
- tests for formatDate
- move sign in function to seperate component
- use fetch data for current functionalities

Wolo 187 details component edit

---

public/locales/en/translation.json
public/locales/pl/translation.json
public/locales/ru/translation.json
public/locales/ua/translation.json
src/Components/Details/Details.js
src/Components/Details/SignedInVolunteers/ShiftEntry.js
src/Components/Details/SignedInVolunteers/SignedInVolunteers.js
src/Components/Details/SignedInVolunteers/VolunteerEntry.js
src/styles/common.scss
src/styles/shift-entry.scss
src/styles/signed-in-volunteers.scss
src/styles/volunteer-entry.scss

Jira: https://woloapp.atlassian.net/browse/WOLO-176
- component for participants -> for now added under details

Wolo 176 signed in volunteers

---

src/Components/Details/Details.js
src/Components/Filters/Filters.js
src/Components/Hero/Hero.js
src/Components/Login/Login.js
src/Components/OrganiserCreateEvent/OrganiserCreateEvent.js
src/Components/Signup/Signup.js
src/config.js

exporting all URLs to one file

WOLO-00-config.js

---

src/Components/Details/Details.js
src/Components/EventCard/EventCard.js
src/Utils/formatDate.js
src/styles/event-card.scss

WOLO-221-card event fixes
Jira: https://woloapp.atlassian.net/browse/WOLO-221
- needed and signed in joined to one field,
- date fixed
- icon added

WOLO-221-card event fixes

---

package-lock.json
package.json
public/index.html
src/App.css
src/Components/AdminHomePage/AdminHomePage.js
src/output.css
src/styles/admin-home-page.scss
tailwind.config.js

Jira: https://woloapp.atlassian.net/browse/WOLO-192
- for now the only thing it is - IT EXISTS
- data from api
- don't think about translations or design right now, functionality first, design will be in may

Wolo 192 admin panel

---

src/Components/Details/SignedInVolunteers/SignedInVolunteers.js
src/config.js

Jira: https://woloapp.atlassian.net/browse/WOLO-199
- checked with backend, works fine

WOLO-199- pdf export download

---

src/Views/Details/ShiftCard/ShiftCard.js
src/Views/Details/SignedInVolunteers/SignedInVolunteers.js
src/Views/VolunteerHomePage/YourEventVolunteer/YourEventVolunteer.js

WOLO-00 Fix routes

---

src/Utils/fetchDataWithNavigate.js
src/Utils/fetchUser.js
src/Utils/fetchUserData.js
src/Utils/postRequest.js
src/Views/Details/Details.js
src/Views/Details/ShiftCard/ShiftCard.js
src/Views/Organiser/Organiser.js

No Jira
Made universal utils:
- fetchUser -> returns all info about user (example in Details)
- fetchData -> deleted navigate from there
- fetchDataWithAuth -> no changes
- fetchDataWithNavigate -> fetchData but if response is anything but ok it redirects to /events, example in Organiisations page
- postRequest -> moved from shiftCard to utils

Wolo 00 utils fix

---

src/Components/Filters/Filters.js
src/Components/Filters/FiltersContext.js

Fixed formating
Events show now from current date into future
Resert button also set up current Date

WOLO-262-display-events

---

src/App.js
src/Views/Login/Login.js

removed google button
change style a litle
forcing refresh

WOLO-246-Login-Bug

---

src/Components/AdminComponents/UsersTab.js
src/Components/AdminComponents/addRecordModals/AddUser.js

Jira: https://woloapp.atlassian.net/browse/WOLO-240
- user can be added thru admin panel

WOLO-240 add user

---

src/Components/AdminComponents/EventsTab.js
src/Components/AdminComponents/OrganisationsTab.js

Jira:
https://woloapp.atlassian.net/browse/WOLO-243
- details for organisation
- details for events
- no styling

Details for events and organisations

---

src/Components/EventCard/EventCard.js
src/Components/Filters/Filters.js
src/Components/OrganiserEventListDisplay/OrganiserEventListDisplay.js
src/Views/Details/Details.js
src/Views/Details/ShiftCard/ShiftCard.js
src/Views/VolunteerHomePage/VolunteerHomePage.js
src/Views/VolunteerHomePage/YourEventVolunteer/YourEventVolunteer.js

https://woloapp.atlassian.net/browse/WOLO-265
- details display
- shift card
- event card
- organisation home page
- volunteer home page
- all events

Wolo 265 ai changes included

---

src/Components/AdminComponents/OrganisationsTab.js
src/Utils/deleteRequest.js
src/config.js

https://woloapp.atlassian.net/browse/WOLO-198
- deleting organisation changes status
- display flag

Wolo 198 delete organisation admin panel

---

src/Components/AdminComponents/OrganisationsTab.js
src/Views/Organiser/Organiser.js

- creating organisation with language for AI
- dynamic change description language  in http://localhost:3000/organiser?organisationId=1

organiser ai translations

---

src/Components/AdminComponents/CategoriesTab.js
src/config.js

https://woloapp.atlassian.net/browse/WOLO-198
- admiin panel category delte

Wolo 198 delete category

---

src/Components/AdminComponents/UsersTab.js

Jira: https://woloapp.atlassian.net/browse/WOLO-198
- user information details
- delete user from admin panel

user details, delete

---

src/Views/Details/Details.js

Update 'More from this Organizer' section to display only future events

WOLO-264-show-only-future-events

---

src/Views/Hero/Hero.js

Jira: https://woloapp.atlassian.net/browse/WOLO-289

No duplicate filters

---

src/Views/Details/Details.js
src/Views/Details/ShiftCard/ShiftCard.js
src/styles/event-card.scss

Jira: https://woloapp.atlassian.net/browse/WOLO-283
Brak wydarzenia z agreementSigned apparently

Wolo 283 requirements for shift card

---

src/App.js
src/Components/Navbar/Navbar.js
src/Views/ForVolunteers/ForVolunteers.js
src/config.js
src/styles/faq.scss

Jira: https://woloapp.atlassian.net/browse/WOLO-292
Why do I have to refresh ;-;

display faq

---

src/config.js

WOLO-00 remove duplicates

---

src/Components/AdminComponents/CategoriesTab.js
src/Components/AdminComponents/CitiesTab.js
src/Components/AdminComponents/DistrictsTab.js
src/Components/AdminComponents/OrganisationsTab.js
src/Components/AdminComponents/UsersTab.js

Jira: https://woloapp.atlassian.net/browse/WOLO-204
- rest search for admin panel

Wolo 204 search admin panel

---

src/Views/Details/Details.js
src/Views/Details/ShiftCard/ShiftCard.js
src/styles/details.scss

https://woloapp.atlassian.net/browse/WOLO-296
shifts on scroll

WOLO-296 shifts on scroll

---

public/locales/en/translation.json
public/locales/pl/translation.json
public/locales/ru/translation.json
public/locales/ua/translation.json
src/Components/AdminComponents/CategoriesTab.js
src/Components/AdminComponents/CitiesTab.js
src/Components/AdminComponents/DistrictsTab.js
src/Components/AdminComponents/EventsTab.js
src/Components/AdminComponents/FAQTab.js
src/Components/AdminComponents/OrganisationsTab.js
src/Components/AdminComponents/UsersTab.js

https://woloapp.atlassian.net/browse/WOLO-245

Wolo 245 admin panel translations

---

src/Components/AdminComponents/CategoriesTab.js
src/Components/AdminComponents/CitiesTab.js
src/Components/AdminComponents/DistrictsTab.js
src/Components/AdminComponents/EventsTab.js
src/Components/AdminComponents/FAQTab.js
src/Components/AdminComponents/OrganisationsTab.js
src/Components/AdminComponents/UsersTab.js

Jira: https://woloapp.atlassian.net/browse/WOLO-312

WOLO-312 admin panel sort records

---

src/Views/Login/Login.js

Removed buggy code so console is no longer red :)

WOLO-00-login-page-errors

---

public/locales/en/translation.json
public/locales/pl/translation.json
public/locales/ru/translation.json
public/locales/ua/translation.json
src/Components/AdminComponents/CitiesTab.js
src/Components/AdminComponents/DistrictsTab.js

https://woloapp.atlassian.net/browse/WOLO-198
- cities
-distrcist

Wolo 198 delete for admin panel - cities, districts

---

src/App.js
src/Components/Navbar/Navbar.js
src/Views/Details/Details.js
src/Views/OrganiserHomePage/OrganiserHomePage.js
src/Views/Reports/Reports.js

No jira, changed urls style from
organiserHomePage
to
organisation-home-page

WOLO00 snake case

---

src/Components/AdminComponents/CategoriesTab.js
src/Components/AdminComponents/CitiesTab.js
src/Components/AdminComponents/DistrictsTab.js
src/Components/AdminComponents/EventsTab.js
src/Components/AdminComponents/FAQTab.js
src/Components/AdminComponents/OrganisationsTab.js
src/Components/AdminComponents/UsersTab.js

Jira: https://woloapp.atlassian.net/browse/WOLO-203
- pagination for all for admin panel

Wolo 203 paginate for admin panel

---

src/Components/AdminComponents/EventsTab.js
src/Components/Navbar/Navbar.js
src/Components/OrganiserEventListDisplay/OrganiserEventListDisplay.js
src/Components/OrganiserEventListDisplay/editModals/EditEventByOrganisation.js
src/Components/OrganiserEventListDisplay/editModals/EditShiftByOrganisation.js
src/config.js
src/styles/organiser-event-list-display.scss

WOLO-205 Edit event for organisations

---

public/locales/en/translation.json
public/locales/pl/translation.json
public/locales/ru/translation.json
public/locales/ua/translation.json
src/Components/AdminComponents/addRecordModals/AddCategory.js
src/Components/AdminComponents/addRecordModals/AddCity.js
src/Components/AdminComponents/addRecordModals/AddDistricts.js
src/Components/AdminComponents/addRecordModals/AddFAQ.js
src/Components/AdminComponents/addRecordModals/AddOrganisation.js
src/Components/AdminComponents/addRecordModals/AddUser.js
src/Components/AdminComponents/editRecordModals/EditCategory.js
src/Components/AdminComponents/editRecordModals/EditCity.js
src/Components/AdminComponents/editRecordModals/EditDistrict.js
src/Components/AdminComponents/editRecordModals/EditEvent.js
src/Components/AdminComponents/editRecordModals/EditFAQ.js
src/Components/AdminComponents/editRecordModals/EditOrganisation.js
src/Components/AdminComponents/editRecordModals/EditShift.js
src/Components/AdminComponents/editRecordModals/EditUser.js
src/Components/OrganiserEventListDisplay/editModals/EditEventByOrganisation.js
src/Components/OrganiserEventListDisplay/editModals/EditShiftByOrganisation.js

Added translations to modules
It's going to be easy they said... It's going to be fun they said ...

Wolo-00 add admin translations
